### ISSUE TITLE
Set up HTTPS on Elastic Beanstalk app

### ISSUE THREAD

**Issue by grahammcculloch** [cshc/cshc-web#3]
Refs: 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-ssl.html
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https.html
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-python.html

http://blog.lookfar.com/blog/2017/05/18/how-to-add-ssl-to-a-single-instance-ebs-server-for-a-node-js-app/

**Comment by mwk20** [comment]
Committed to master in 1e178b0.

Remove duplicate configuration of event mpm module and wsgi module.
Install mod_ssl.
LetsEncrypt installation problematic (should probably be in AMI) so output files flattened into configuration.
Configure WSGISSL virtualhost using uniquely named WSGI process group.
